/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.saberpro.Vista;

import com.mycompany.saberpro.Modelo.ConsultasUsuario;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author juanf
 */
public class InterConsultasU extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterConsultasU
     */
    ConsultasUsuario modelo = new ConsultasUsuario();

    public InterConsultasU() {
        initComponents();
        this.setResizable(false);
        this.setClosable(true);
        this.setIconifiable(true);
        this.setSize(new Dimension(990, 605));
        this.setTitle("CONSULTAS DE USUARIOS");
        javax.swing.table.JTableHeader header = jTable.getTableHeader();
        header.setFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 14));
        cargarComboRol();
        cargarComboEstado();
        cargarTablaConTodos();

    }

    private void cargarComboRol() {
        boxRol.removeAllItems();
        boxRol.addItem("Todos");

        try (ResultSet rs = modelo.obtenerRoles()) {
            while (rs.next()) {
                boxRol.addItem(rs.getString("rol"));
            }
        } catch (SQLException e) {
            System.err.println("Error cargando roles: " + e.getMessage());
        }
    }

    private void cargarComboEstado() {
        boxEstado.removeAllItems();
        boxEstado.addItem("Todos");
        boxEstado.addItem("Habilitado");
        boxEstado.addItem("Inhabilitado");
    }

    private void cargarTabla(ResultSet rs) throws SQLException {
        String[] columnas = {"Nombre", "Apellido", "Telefono", "CC", "Correo", "Habilitado", "Rol", "Fecha Inicio", "Fecha Fin"};
        javax.swing.table.DefaultTableModel modeloTabla = new javax.swing.table.DefaultTableModel(columnas, 0);

        while (rs.next()) {
            Object[] fila = {
                rs.getString("nombre"),
                rs.getString("apellido"),
                rs.getString("telefono"),
                rs.getString("cc"),
                rs.getString("correo"),
                rs.getBoolean("habilitado"),
                rs.getString("rol"),
                rs.getTimestamp("fecha_inicio"),
                rs.getTimestamp("fecha_fin")
            };
            modeloTabla.addRow(fila);
        }

        jTable.setModel(modeloTabla);
    }

    private void cargarTablaConTodos() {
        try {
            ResultSet rs = modelo.consultarUsuarios("", "Todos", "Todos", null, null, false);
            cargarTabla(rs);
        } catch (SQLException e) {
            System.err.println("Error cargando tabla: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        dateFin = new com.toedter.calendar.JDateChooser();
        dateInicio = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        boxEstado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        boxRol = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        iTable = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(94, 122, 178));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimpiar.setBackground(new java.awt.Color(0, 0, 153));
        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 90, -1));
        jPanel1.add(dateFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 220, -1));
        jPanel1.add(dateInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 240, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha Inicio");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rol");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        boxEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(boxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 160, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha Fin");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        boxRol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(boxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 240, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Estado");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        txtBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 660, -1));

        btnBuscar.setBackground(new java.awt.Color(0, 0, 153));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 90, -1));

        iTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Telefono", "CC", "Correo", "Habilitado", "Rol", "Fecha inicio", "Fecha fin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        iTable.setViewportView(jTable);

        jPanel1.add(iTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 910, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtBuscar.setText("");
        boxRol.setSelectedIndex(0);
        boxEstado.setSelectedIndex(0);
        dateInicio.setDate(null);
        dateFin.setDate(null);
        cargarTablaConTodos();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> boxEstado;
    public javax.swing.JComboBox<String> boxRol;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnLimpiar;
    public com.toedter.calendar.JDateChooser dateFin;
    public com.toedter.calendar.JDateChooser dateInicio;
    private javax.swing.JScrollPane iTable;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTable jTable;
    public javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
