/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.saberpro.Vista;

import com.mycompany.saberpro.Modelo.EstudianteSeleccionado;
import com.mycompany.saberpro.Modelo.Usuario;
import java.awt.BorderLayout;
import java.awt.Dimension;

/**
 *
 * @author juanf
 */
public class InterResultadoPersonal extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterResultadoPersonal
     */
    private Integer idUsuario;     // estudiante logueado
    private String cc;             // selección manual
    private String numeroRegistro;
    private Integer anio;
    private Integer semestre;

    public InterResultadoPersonal() {
        initComponents();
        this.setResizable(false);
        this.setClosable(true);
        this.setIconifiable(true);
        this.setSize(new Dimension(1063, 707));
        this.setTitle("RESULTADOS");

        // 1. Venimos desde InterPersonal (selección explícita)
        if (EstudianteSeleccionado.getNumeroRegistro() != null
                || EstudianteSeleccionado.getCc() != null) {

            this.cc = EstudianteSeleccionado.getCc();
            this.numeroRegistro = EstudianteSeleccionado.getNumeroRegistro();
            this.anio = EstudianteSeleccionado.getAnio();
            this.semestre = EstudianteSeleccionado.getSemestre();
            this.idUsuario = null; // en este flujo no lo usamos

            // 2. Venimos como estudiante logueado directo desde el menú
        } else if (Usuario.usuarioActual != null) {

            this.idUsuario = Usuario.usuarioActual.getId_usuario();
            this.cc = null;
            this.numeroRegistro = null;
            this.anio = null;
            this.semestre = null;

            // buscamos cc, año y semestre de su última prueba
            cargarDatosUltimaPrueba();

        } else {
            this.idUsuario = null;
            this.cc = null;
            this.numeroRegistro = null;
            this.anio = null;
            this.semestre = null;
        }

        // Panel inicial: Globales
        Globales p1 = new Globales(idUsuario, cc, numeroRegistro);
        p1.setSize(719, 410);
        p1.setLocation(0, 0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    private void cargarDatosUltimaPrueba() {
        if (idUsuario == null) {
            return;
        }

        String sql
                = "SELECT e.cc, r.codigo AS numero_registro, p.ano, p.semestre "
                + "FROM estudiante e "
                + "JOIN prueba   p ON p.id_estudiante = e.id_estudiante "
                + "JOIN registro r ON r.id_registro   = p.id_registro "
                + "WHERE e.id_usuario = ? "
                + "ORDER BY p.ano DESC, p.semestre DESC "
                + "LIMIT 1";

        try (java.sql.Connection con = new com.mycompany.saberpro.Modelo.Conexion().getConexion(); java.sql.PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, idUsuario);

            try (java.sql.ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    this.cc = rs.getString("cc");
                    this.numeroRegistro = rs.getString("numero_registro");
                    this.anio = rs.getInt("ano");
                    this.semestre = rs.getInt("semestre");
                }
            }

        } catch (Exception ex) {
            System.err.println("Error obteniendo datos de la última prueba: " + ex.getMessage());
        }
    }

    public Integer getIdUsuario() {
        return idUsuario;
    }

    public String getCc() {
        return cc;
    }

    public String getNumeroRegistro() {
        return numeroRegistro;
    }

    public Integer getAnio() {
        return anio;
    }

    public Integer getSemestre() {
        return semestre;
    }
    // </editor-fold>                        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnModulo = new javax.swing.JButton();
        btnGlobales = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnDesempeño = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModulo.setText("Resultados por Módulo");
        btnModulo.setBorderPainted(false);
        btnModulo.setContentAreaFilled(false);
        btnModulo.setFocusPainted(false);
        btnModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloActionPerformed(evt);
            }
        });
        getContentPane().add(btnModulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 230, 40));

        btnGlobales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGlobales.setText("Resultados Globales");
        btnGlobales.setBorderPainted(false);
        btnGlobales.setContentAreaFilled(false);
        btnGlobales.setFocusPainted(false);
        btnGlobales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGlobalesActionPerformed(evt);
            }
        });
        getContentPane().add(btnGlobales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDesempeño.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDesempeño.setText("Generales");
        btnDesempeño.setBorderPainted(false);
        btnDesempeño.setContentAreaFilled(false);
        btnDesempeño.setFocusPainted(false);
        btnDesempeño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesempeñoActionPerformed(evt);
            }
        });
        jPanel2.add(btnDesempeño, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 270, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 40));

        content.setLayout(new java.awt.BorderLayout());
        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1050, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGlobalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGlobalesActionPerformed
        Globales p1 = new Globales(idUsuario, cc, numeroRegistro);
        p1.setSize(719, 410);
        p1.setLocation(0, 0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnGlobalesActionPerformed

    private void btnDesempeñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesempeñoActionPerformed
        Estadisticos p3 = new Estadisticos(anio, semestre);
        p3.setSize(719, 410);
        p3.setLocation(0, 0);

        content.removeAll();
        content.add(p3, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnDesempeñoActionPerformed

    private void btnModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloActionPerformed
        Modulos p2 = new Modulos(idUsuario, cc, numeroRegistro, anio, semestre);
        p2.setSize(719, 410);
        p2.setLocation(0, 0);

        content.removeAll();
        content.add(p2, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnModuloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesempeño;
    private javax.swing.JButton btnGlobales;
    private javax.swing.JButton btnModulo;
    private javax.swing.JPanel content;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
