/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.saberpro.Vista;

import com.mycompany.saberpro.Modelo.Usuario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author juanf
 */
public class InterCuenta extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterCuenta
     */
    public InterCuenta() {
        initComponents();
        this.setResizable(false);
        this.setResizable(false);
        this.setClosable(true);
        this.setIconifiable(true);
        this.setTitle("GESTION DE CUENTA");
        this.setSize(new Dimension(659, 396));
        Usuario u = Usuario.usuarioActual;
        if (u != null) {
            txtCodigo.setText(String.valueOf(u.getId_usuario()));
            txtNombre.setText(u.getNombre());
            txtApellido.setText(u.getApellido());
            txtCC.setText(u.getCc());
            txtTelefono.setText(u.getTelefono());
            txtCorreo.setText(u.getCorreo());
            txtContrasena.setText(u.getContrasena());

            // Bloquear campos no editables
            txtCodigo.setEditable(false);
            txtNombre.setEditable(false);
            txtApellido.setEditable(false);
            txtCC.setEditable(false);
            txtCC.setBackground(Color.LIGHT_GRAY);
            txtCodigo.setBackground(Color.LIGHT_GRAY);
            txtNombre.setBackground(Color.LIGHT_GRAY);
            txtApellido.setBackground(Color.LIGHT_GRAY);
        }
        try {
            ImageIcon iconoAbierto = new ImageIcon(
                    new ImageIcon(getClass().getResource("/img/cerrado.png"))
                            .getImage().getScaledInstance(24, 24, Image.SCALE_SMOOTH)
            );

            ImageIcon iconoCerrado = new ImageIcon(
                    new ImageIcon(getClass().getResource("/img/abierto.png"))
                            .getImage().getScaledInstance(24, 24, Image.SCALE_SMOOTH)
            );

            tglMostrarContraseña.setIcon(iconoAbierto);
            tglMostrarContraseña.setSelectedIcon(iconoCerrado);
            tglMostrarContraseña.setBorderPainted(false);
            tglMostrarContraseña.setContentAreaFilled(false);
            

        } catch (Exception e) {
            System.err.println("No se pudieron cargar los iconos del toggle: " + e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        txtContrasena = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCC = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tglMostrarContraseña = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Codigo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Correo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contraseña");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        txtCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 350, -1));

        txtCorreo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 350, -1));

        btnActualizar.setBackground(new java.awt.Color(0, 0, 153));
        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        txtContrasena.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtContrasena.setEchoChar('*');
        getContentPane().add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 350, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CC");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Apellido");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombre");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        txtCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 350, -1));

        txtApellido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 350, -1));

        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 350, -1));

        txtTelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 350, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Telefono");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        tglMostrarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglMostrarContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(tglMostrarContraseña);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 30, 30));

        jPanel2.setBackground(new java.awt.Color(94, 122, 178));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tglMostrarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglMostrarContraseñaActionPerformed
        if (tglMostrarContraseña.isSelected()) {
            txtContrasena.setEchoChar((char) 0); // mostrar contraseña
        } else {
            txtContrasena.setEchoChar('*'); // ocultar contraseña
        }
    }//GEN-LAST:event_tglMostrarContraseñaActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton tglMostrarContraseña;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtCC;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JPasswordField txtContrasena;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
