/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.saberpro.Vista;

import com.mycompany.saberpro.Modelo.Conexion;
import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanf
 */
public class InterCargaUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterCargaUsuario
     */
    public InterCargaUsuario() {
        initComponents();
        this.setSize(new Dimension(597, 444));
        this.setTitle("CARGAR MASIVA DE USUARIOS");
    }

    private String generarContrasena() {
        // Genera una contraseña parecida a las de Google
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%&*";
        StringBuilder pass = new StringBuilder();
        for (int i = 0; i < 10; i++) {
            int index = (int) (Math.random() * chars.length());
            pass.append(chars.charAt(index));
        }

        return pass.toString();

    }

    private List<String> parseCsvLine(String linea) {
        List<String> campos = new ArrayList<>();
        StringBuilder sb = new StringBuilder();
        boolean dentroComillas = false;

        for (char c : linea.toCharArray()) {
            if (c == '"') {
                dentroComillas = !dentroComillas;
            } else if ((c == ',' || c == ';') && !dentroComillas) {
                campos.add(sb.toString().trim());
                sb.setLength(0);
            } else {
                sb.append(c);
            }
        }
        campos.add(sb.toString().trim()); // último campo
        return campos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnCargar = new javax.swing.JButton();
        btnExaminar = new javax.swing.JButton();
        txtArchivo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Telefono", "CC", "Correo", "id_rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jScrollPane3.setViewportView(jScrollPane2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 530, 190));

        btnCargar.setBackground(new java.awt.Color(0, 0, 153));
        btnCargar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCargar.setForeground(new java.awt.Color(255, 255, 255));
        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 124, -1));

        btnExaminar.setBackground(new java.awt.Color(0, 0, 153));
        btnExaminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExaminar.setForeground(new java.awt.Color(255, 255, 255));
        btnExaminar.setText("Examinar");
        btnExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExaminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnExaminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 120, -1));

        txtArchivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 110, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cargar archivo de usuarios:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 210, -1));

        jPanel1.setBackground(new java.awt.Color(94, 122, 178));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        String ruta = txtArchivo.getText();
        if (ruta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona un archivo primero.");
            return;
        }

        File archivo = new File(ruta);
        if (!archivo.exists()) {
            JOptionPane.showMessageDialog(this, "El archivo no existe.");
            return;
        }

        // ============================
        //  Validar extensión .csv
        // ============================
        String rutaLower = ruta.toLowerCase();
        if (!rutaLower.endsWith(".csv")) {
            JOptionPane.showMessageDialog(this,
                    "El archivo debe estar en formato CSV (.csv).",
                    "Formato inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ============================
        //  Modelo de la tabla visual
        // ============================
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Teléfono");
        modelo.addColumn("CC");
        modelo.addColumn("Correo");
        modelo.addColumn("Rol");
        jTable2.setModel(modelo);

        Conexion conexion = new Conexion();
        Connection conn = conexion.getConexion();

        if (conn == null) {
            JOptionPane.showMessageDialog(this, "No se pudo conectar a la base de datos.");
            return;
        }

        StringBuilder errores = new StringBuilder();

        try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {

            // ===========================================
            // 1) LEER Y VALIDAR ENCABEZADO DEL CSV
            // ===========================================
            String header = br.readLine();
            if (header == null) {
                JOptionPane.showMessageDialog(this,
                        "El archivo CSV está vacío.",
                        "Archivo vacío", JOptionPane.WARNING_MESSAGE);
                return;
            }

            List<String> headerCampos = parseCsvLine(header);
            String[] requeridas = {"nombre", "apellido", "telefono", "cc", "correo", "rol"};

// Por si Excel mete BOM u otros caracteres raros
            boolean headerValido = headerCampos.size() >= requeridas.length;
            for (int i = 0; i < requeridas.length && headerValido; i++) {
                String valor = headerCampos.get(i)
                        .toLowerCase()
                        .replace("\uFEFF", "") // quita el BOM si viene pegado a "nombre"
                        .trim();

                // System.out.println("Columna " + i + ": '" + valor + "'");  // si quieres probar
                if (!valor.equals(requeridas[i])) {
                    headerValido = false;
                }
            }
            if (!headerValido) {
                JOptionPane.showMessageDialog(this,
                        "El archivo CSV debe tener como primeras columnas (en este orden):\n"
                        + "nombre, apellido, telefono, cc, correo, rol",
                        "Encabezado inválido", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // ===========================================
            // 2) PROCESAR CADA FILA DE DATOS
            // ===========================================
            String linea;
            while ((linea = br.readLine()) != null) {
                linea = linea.trim();
                if (linea.isEmpty()) {
                    continue; // Ignorar líneas vacías
                }

                List<String> campos = parseCsvLine(linea);

                if (campos.size() < 6) {
                    errores.append("Fila incompleta: ").append(linea).append("\n");
                    continue;
                }

                String nombre = campos.get(0);
                String apellido = campos.get(1);
                String telefono = campos.get(2);
                String cc = campos.get(3);
                String correo = campos.get(4);
                String rolTexto = campos.get(5).toLowerCase();

                int idRol;
                switch (rolTexto) {
                    case "profesor":
                        idRol = 6;
                        break;
                    case "estudiante":
                        idRol = 4;
                        break;
                    default:
                        errores.append("Rol inválido '").append(rolTexto)
                                .append("' para el correo ").append(correo)
                                .append(" (no existe tabla para ese rol).\n");
                        continue; // saltar fila
                }

                // ============================
                // 3) Validar correo duplicado
                // ============================
                String checkCorreoSQL = "SELECT COUNT(*) FROM usuario WHERE correo = ?";
                try (PreparedStatement psCheckCorreo = conn.prepareStatement(checkCorreoSQL)) {
                    psCheckCorreo.setString(1, correo);
                    try (ResultSet rsCorreo = psCheckCorreo.executeQuery()) {
                        if (rsCorreo.next() && rsCorreo.getInt(1) > 0) {
                            errores.append("El correo ").append(correo)
                                    .append(" ya está registrado. Fila omitida.\n");
                            continue;
                        }
                    }
                }

                // ============================
                // 4) Validar CC duplicada
                // ============================
                String checkCcSQL = "SELECT COUNT(*) FROM vista_cc_global WHERE cc = ?";
                try (PreparedStatement psCheckCc = conn.prepareStatement(checkCcSQL)) {
                    psCheckCc.setString(1, cc);
                    try (ResultSet rsCc = psCheckCc.executeQuery()) {
                        if (rsCc.next() && rsCc.getInt(1) > 0) {
                            errores.append("La cédula ").append(cc)
                                    .append(" ya está registrada. Fila omitida.\n");
                            continue;
                        }
                    }
                }

                // ============================
                // 5) Generar contraseña
                // ============================
                String contrasena = generarContrasena();

                try {
                    // ============================
                    // 6) Insertar en usuario
                    // ============================
                    int idUsuario = 0;
                    String sqlUsuario = "INSERT INTO usuario (correo, contrasena, id_roles, habilitado) "
                            + "VALUES (?, ?, ?, TRUE) RETURNING id_usuario";
                    try (PreparedStatement psUsuario = conn.prepareStatement(sqlUsuario)) {
                        psUsuario.setString(1, correo);
                        psUsuario.setString(2, contrasena);
                        psUsuario.setInt(3, idRol);

                        try (ResultSet rs = psUsuario.executeQuery()) {
                            if (rs.next()) {
                                idUsuario = rs.getInt("id_usuario");
                            } else {
                                errores.append("No se pudo obtener id_usuario para correo ")
                                        .append(correo).append("\n");
                                continue;
                            }
                        }
                    }

                    // ============================
                    // 7) Insertar en tabla de rol
                    // ============================
                    String sqlInsert;
                    if (idRol == 6) { // profesor
                        sqlInsert = "INSERT INTO profesor (nombre, apellido, telefono, cc, id_usuario) "
                                + "VALUES (?, ?, ?, ?, ?)";
                    } else {          // estudiante
                        sqlInsert = "INSERT INTO estudiante (nombre, apellido, telefono, cc, id_usuario) "
                                + "VALUES (?, ?, ?, ?, ?)";
                    }

                    try (PreparedStatement psExtra = conn.prepareStatement(sqlInsert)) {
                        psExtra.setString(1, nombre);
                        psExtra.setString(2, apellido);
                        psExtra.setString(3, telefono);
                        psExtra.setString(4, cc);
                        psExtra.setInt(5, idUsuario);
                        psExtra.executeUpdate();
                    }

                    // ============================
                    // 8) Insertar en HISTORIAL
                    // ============================
                    String sqlHist = "INSERT INTO historial (id_usuario, id_roles, fecha_inicio) "
                            + "VALUES (?, ?, NOW())";
                    try (PreparedStatement psHist = conn.prepareStatement(sqlHist)) {
                        psHist.setInt(1, idUsuario);
                        psHist.setInt(2, idRol);
                        psHist.executeUpdate();
                    }

                    // ============================
                    // 9) Agregar fila a la tabla visual
                    // ============================
                    modelo.addRow(new Object[]{nombre, apellido, telefono, cc, correo, rolTexto});

                } catch (SQLException exFila) {
                    errores.append("Error al insertar usuario con correo ")
                            .append(correo).append(": ")
                            .append(exFila.getMessage()).append("\n");
                    exFila.printStackTrace();
                }
            }

            conn.close();

            // Mensaje final
            StringBuilder msgFinal = new StringBuilder("Carga masiva finalizada.\n");
            msgFinal.append("Revisa la tabla para ver los usuarios cargados.\n");
            if (errores.length() > 0) {
                msgFinal.append("\nSe omitieron algunas filas por errores:\n")
                        .append(errores);
            }

            JOptionPane.showMessageDialog(this, msgFinal.toString());

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error leyendo el archivo: " + e.getMessage());
            e.printStackTrace();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de base de datos: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExaminarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos CSV (*.csv)", "csv");
        fileChooser.setFileFilter(filtro);

        int seleccion = fileChooser.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            txtArchivo.setText(archivo.getAbsolutePath());
        }
    }//GEN-LAST:event_btnExaminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnExaminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtArchivo;
    // End of variables declaration//GEN-END:variables
}
