/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.saberpro.Vista;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author juanf
 */
public class InterPersonales extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterPersonales
     */
    public InterPersonales() {
        initComponents();
        this.setResizable(false);
        this.setClosable(true);
        this.setIconifiable(true);
        this.setSize(new Dimension(848, 520));
        this.setTitle("CONSULTAR POR ESTUDIANTE");
        tablaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"Nombre", "Apellido", "CC", "Número de registro"}
        ));
    }

    public javax.swing.JTextField getTxtEstudiante() {
        return txtEstudiante;
    }

    public javax.swing.JTextField getTxtCC() {
        return txtCC;
    }

    public javax.swing.JButton getBtnBuscar() {
        return btnBuscar;
    }

    public javax.swing.JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    public javax.swing.JButton getBtnSeleccionar() {
        return btnSeleccionar;
    }

    public javax.swing.JTable getTablaEstudiantes() {
        return tablaEstudiantes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEstudiante = new javax.swing.JTextField();
        txtCC = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstudiantes = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 51));

        jPanel1.setBackground(new java.awt.Color(94, 122, 178));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CC");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Estudiante");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        txtEstudiante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 510, -1));

        txtCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 170, -1));

        btnLimpiar.setBackground(new java.awt.Color(0, 0, 153));
        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 130, 30));

        btnSeleccionar.setBackground(new java.awt.Color(0, 0, 153));
        btnSeleccionar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 130, 30));

        tablaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "CC", "Número de registro", "Año", "Semestre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaEstudiantes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 770, 230));

        btnBuscar.setBackground(new java.awt.Color(0, 0, 153));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        int fila = tablaEstudiantes.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un estudiante de la tabla.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // OJO: índices según el orden de columnas de la tabla:
        // 0=Nombre, 1=Apellido, 2=CC, 3=Número de registro, 4=Año, 5=Semestre
        String cc = String.valueOf(tablaEstudiantes.getValueAt(fila, 2));
        String numeroRegistro = String.valueOf(tablaEstudiantes.getValueAt(fila, 3));

        // Año y semestre como Integer (puedes manejarlos como String si quieres)
        Integer anio = null;
        Integer semestre = null;

        Object valAnio = tablaEstudiantes.getValueAt(fila, 4);
        Object valSem = tablaEstudiantes.getValueAt(fila, 5);

        if (valAnio != null && !valAnio.toString().trim().isEmpty()) {
            try {
                anio = Integer.valueOf(valAnio.toString().trim());
            } catch (NumberFormatException e) {
                // si no es numérico lo dejamos null
            }
        }
        if (valSem != null && !valSem.toString().trim().isEmpty()) {
            try {
                semestre = Integer.valueOf(valSem.toString().trim());
            } catch (NumberFormatException e) {
            }
        }

        // Guardamos la selección globalmente (incluyendo año y semestre)
        com.mycompany.saberpro.Modelo.EstudianteSeleccionado
                .setSeleccion(cc, numeroRegistro, anio, semestre);

        // Abrimos directamente InterResultadoPersonal en el mismo DesktopPane
        InterResultadoPersonal frm = new InterResultadoPersonal();
        getDesktopPane().add(frm);
        frm.setVisible(true);

        // Cerramos esta ventana de búsqueda
        dispose();
    }//GEN-LAST:event_btnSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEstudiantes;
    private javax.swing.JTextField txtCC;
    private javax.swing.JTextField txtEstudiante;
    // End of variables declaration//GEN-END:variables
}
