/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.saberpro.Vista;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
    
/**
 *
 * @author juanf
 */
public class PanelPercentil extends javax.swing.JPanel {
    // valor 0–100

    private double percentil = 0;

    public PanelPercentil() {
        setOpaque(false); // para que respete el fondo del formulario
    }

    public void setPercentil(double percentil) {
        // lo dejamos entre 0 y 100
        this.percentil = Math.max(0, Math.min(100, percentil));
        repaint();
    }

    public double getPercentil() {
        return percentil;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON);

        int paddingX = 40;         // espacio a los lados
        int y = getHeight() / 2;   // altura de la línea
        int x0 = paddingX;
        int x1 = getWidth() - paddingX;

        // ---------------------------
        // 1) Línea base gris clarita
        // ---------------------------
        g2.setStroke(new BasicStroke(10f, BasicStroke.CAP_ROUND,
                BasicStroke.JOIN_ROUND));
        g2.setColor(new Color(220, 220, 220));
        g2.drawLine(x0, y, x1, y);

        // ---------------------------
        // 2) Parte azul hasta el percentil
        // ---------------------------
        int xPercentil = (int) (x0 + (x1 - x0) * (percentil / 100.0));
        g2.setColor(new Color(0, 122, 255)); // azul
        g2.drawLine(x0, y, xPercentil, y);

        // ---------------------------
        // 3) Marcas 0,20,40,60,80,100
        // ---------------------------
        g2.setStroke(new BasicStroke(2f));
        g2.setColor(new Color(80, 80, 80));
        Font fontTicks = getFont().deriveFont(Font.PLAIN, 12f);
        g2.setFont(fontTicks);

        for (int p = 0; p <= 100; p += 20) {
            int x = x0 + (x1 - x0) * p / 100;
            // palito
            g2.drawLine(x, y - 8, x, y + 8);
            // texto debajo
            String txt = String.valueOf(p);
            int w = g2.getFontMetrics().stringWidth(txt);
            g2.drawString(txt, x - w / 2, y + 25);
        }

        // ---------------------------
        // 4) Número grande del percentil
        // ---------------------------
        String txtPercentil = String.format("%.0f", percentil);
        g2.setFont(getFont().deriveFont(Font.BOLD, 28f));
        int wTxt = g2.getFontMetrics().stringWidth(txtPercentil);
        int hTxt = g2.getFontMetrics().getAscent();

        // lo pongo encima de la barrita, más o menos centrado
        int xTxt = xPercentil - wTxt / 2;
        xTxt = Math.max(x0, Math.min(xTxt, x1 - wTxt)); // que no se salga
        int yTxt = y - 20;

        g2.setColor(new Color(0, 122, 255));
        g2.drawString(txtPercentil, xTxt, yTxt);

        g2.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 878, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
